# Generated by Django 2.2.1 on 2019-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=20)),
                ('recharge_date', models.CharField(max_length=20)),
                ('expire_date', models.CharField(max_length=20)),
                ('select_channel', models.CharField(choices=[('m', 'maatv'), ('z', 'zeetv'), ('e', 'etv'), ('g', 'gemini'), ('n', 'ntv')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
