# Generated by Django 2.2.1 on 2019-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190622_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=20)),
                ('recharge_date', models.CharField(max_length=20)),
                ('expire_date', models.CharField(max_length=20)),
                ('select_channel', models.CharField(choices=[('A', 'Airtel'), ('D', 'Dish tv'), ('T', 'Tata sky'), ('S', 'Sun direct')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
