# Generated by Django 2.2.1 on 2019-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190622_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='select_channel',
            field=models.CharField(choices=[('m', 'maatv'), ('z', 'zeetv'), ('e', 'etv'), ('s', 'sony'), ('b', 'bhakti tv'), ('n', 'ntv')], max_length=20),
        ),
    ]
